### PR TITLE
[url] Suggestion from joinr to improve this predicate.

### LINKED ISSUE #6: tech.v3.io.url/url? improper on windows file-paths, causing tech.v3.io/input-stream to throw
Discovered while messing with tech.ml.dataset on windows, eventually traced down to tech.v3.io.url (default parser that tmd uses for submitting paths for csv/tsv files apparently):

https://github.com/techascent/tech.io/blob/master/src/tech/v3/io/url.clj#L70

given:

(def path "C:\\Users\\joinr\\data\\yellow_tripdata_2016-01.csv")

(.exists (clojure.java.io/file path)) ;;true

(tech.v3.io.url/url? path) ;;:C:\Users\joinr\data\yellow_tripdata_2016-01.cs

(tech.v3.io/input-stream path) 

Execution error (FileNotFoundException) at java.io.FileInputStream/open0 (FileInputStream.java:-2).
C:\Users\joinr\data\yellow_tripdata_2016-01.cs: (The filename, directory name, or volume label syntax is incorrect)

(tech.v3.io.url/url->parts path)
{:protocol :C:\Users\joinr\data\yellow_tripdata_2016-01.cs,  ;;invalid protocol, happens to chop off v as well.
 :path (),
 :arguments nil}

(tech.v3.io.url/url->parts "http://www.blah.com")  
{:protocol :http, :path ("www.blah.com"), :arguments nil} ;;as expected

(tech.v3.io.url/url->parts "c:\\i\\am\\not\\a\\url")
{:protocol :c:\i\am\not\a\ur, :path (), :arguments nil} ;;should throw per the existing semantics..

Proposed solution:

Instead of custom URL parsing in `url?`, try to construct a java.net.URL instance and see if it validly parses.

This patch enables native file paths to work on windows and should strengthen the url? predicate.

[patch.diff](https://github.com/techascent/tech.io/files/6240214/patch.diff.txt)

### PR DESCRIPTION
**Pull request by harold**
- Fixes #6.

### CODE REVIEW

File: src/tech/v3/io/url.clj [hunk 1]
```diff
@@ -1,13 +1,16 @@
 (ns tech.v3.io.url
-  (:require [clojure.string :as string]
-            [clojure.spec.alpha :as s])
+  (:require [clojure.string :as string])
```
Comment (cnuernber) [inline src/tech/v3/io/url.clj:2]: Good call removing spec

**Review by cnuernber — APPROVED** [review]

File: src/tech/v3/io/url.clj (hunk 1 above)
Comment (harold) [reply src/tech/v3/io/url.clj:2]: Joker did it - :hand_over_mouth:
